wr-core: install perl-bignum on Fedora
This package is needed to build openssl, see the following
error on Fedora 25:

ERROR: The perl module 'bignum' was not found but this is required to
build openssl.  Please install this module (often packaged as
perl-bignum) and re-run bitbake.
ERROR: Function failed: do_configure (log file is located at
/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux/openssl-native/1.0.2d-r0/temp/log.do_configure.2043)
ERROR: Logfile of failure stored in:
/buildarea1/ywei/wr-core/build-lanner-lec-2137/tmp/work/x86_64-linux/openssl-native/1.0.2d-r0/temp/log.do_configure.2043
ERROR: Task 223
(virtual:native:/buildarea1/ywei/wr-core/layers/oe-core/meta/recipes-connectivity/openssl/openssl_1.0.2d.bb,
do_configure) failed with exit code '1'

Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>